// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGPLIV2xbjv3WOMymz2xHTm0ZYXEI8_I',
    appId: '1:20795749884:web:54536e77054a7f204bae79',
    messagingSenderId: '20795749884',
    projectId: 'studentdormplatform',
    authDomain: 'studentdormplatform.firebaseapp.com',
    storageBucket: 'studentdormplatform.appspot.com',
    measurementId: 'G-6WHZ9M01P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70rqf0F-QSi4jEWdmKXirdNxlHQaNyHE',
    appId: '1:20795749884:android:6d973989f908c25f4bae79',
    messagingSenderId: '20795749884',
    projectId: 'studentdormplatform',
    storageBucket: 'studentdormplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0ivs9-iSH13NyT4c7P-gaXBRjo24rMs',
    appId: '1:20795749884:ios:a8c2eb3829463acd4bae79',
    messagingSenderId: '20795749884',
    projectId: 'studentdormplatform',
    storageBucket: 'studentdormplatform.appspot.com',
    iosBundleId: 'com.example.studentDormFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0ivs9-iSH13NyT4c7P-gaXBRjo24rMs',
    appId: '1:20795749884:ios:a8c2eb3829463acd4bae79',
    messagingSenderId: '20795749884',
    projectId: 'studentdormplatform',
    storageBucket: 'studentdormplatform.appspot.com',
    iosBundleId: 'com.example.studentDormFrontend',
  );
}
